### ISSUE TITLE
Random tile placement 

### ISSUE THREAD

**Issue by VIRMSKVLL** [Astrabit-ST/Luminol#122]
**Is your feature request related to a problem? Please describe.**
Having lots of tile variations that have to get randomized by hand using the pencil tool and hand distribution.

**Describe the solution you'd like**
a mode to shift the pencil action from placing all the tiles as a bunch to placing a random tile from the selected bunch

**Describe alternatives you've considered**
Instead of a toggle, a different selection mode on the tile picker holding alt to add to a 'randomized bunch'.
Personally I consider the above to be a more sound option.

**Comment by melody-rs** [comment]
Could make alt turn the toggle on while it's held down, so we get the best of both worlds

**Comment by zimberzimber** [comment]
It might be a better idea to have the game handle randomization instead of the editor, so that you can still use tile picker and bucket tools on the tiles that are supposed to be randomized.

**Comment by white-axe** [comment]
That's true but I'll implement this anyways for people who don't know how or are too lazy.
