### ISSUE TITLE
Collision Preview

### ISSUE THREAD

**Issue by CryroFox** [Astrabit-ST/Luminol#22]
**Is your feature request related to a problem? Please describe.**
Often during the latter halfs of the development cycle there's often a lot of missing collision that lets you leave maps or just go somewhere plain weird. It'd be nice to be able to check and view the map collision within the editor so you don't have to use a janky debug script and run around everywhere.

**Describe the solution you'd like**
Some sort of layer toggle button that overlays a red collision indicator (like the pre-existing debug script solution we have with the tileset rn) in the editor on the map, accounting for event collisions too 

**Describe alternatives you've considered**
The debug script we have™

**Additional context**

![image](https://github.com/Astrabit-ST/Luminol/assets/44964856/2308fc39-926c-42fd-8030-7eab08d6b65b)

![image](https://github.com/Astrabit-ST/Luminol/assets/44964856/413c9f31-f3bc-4216-b68f-96febccbb0d4)

**Comment by white-axe** [comment]
Can I be assigned to this issue?

**Comment by melody-rs** [comment]
Sure!
Here's the code that generated these previews (it's a little hacky)
[Mod_Debug.txt](https://github.com/Astrabit-ST/Luminol/files/12925176/Mod_Debug.txt)
It also uses this tileset:
![debug_collision](https://github.com/Astrabit-ST/Luminol/assets/54482069/73492708-8bec-474d-a1d2-3e9695584e4f)
