### ISSUE TITLE
Implement RMXP Extractor Into the Editor

### ISSUE THREAD

**Issue by zimberzimber** [Astrabit-ST/Luminol#28]
## Is your feature request related to a problem? Please describe.
Currently, to extract RMXP scripts the user requires installing Ruby on their machine.
If the functionality were to be implemented into Luminol, users would be able to extract and look through them with one less dependency.
Would be very helpful to users who're new to scripting, and are terrified of touching the console.

## Describe the solution you'd like
- A button that would extract scripts from `Scripts.rxdata` into files in a folder of the users choice
- A button that would compress scripts from a folder of the users choice into a `Scripts.rxdata` file

## Describe alternatives you've considered
Doing it the less user friendly way with the RMXP Extractor gem in a terminal.

**Comment by Speak2Erase** [comment]
What formats should I support?

**Comment by zimberzimber** [comment]
I believe only JSON should be supported as it's the most well known format nowadays.
If someone absolutely needs it in another format, they can always use already available conversion tools.
And you wouldn't need to maintain more than one format converter.

**Comment by white-axe** [comment]
I'm working on a similar UI for archives so I might as well do this too.

**Comment by melody-rs** [comment]
This should probably wait until I finish the alox-48 rewrite. I'm currently re-doing the crate to be detached from serde, so we can have separate deserialize impls for marshal and other serde formats (json/yaml)
