### ISSUE TITLE
Crash webhook

### ISSUE THREAD

**Issue by Speak2Erase** [Astrabit-ST/Luminol#6]

**Comment by white-axe** [comment]
Can you...explain?

**Comment by melody-rs** [comment]
Oh, this is a feature from osfm

In our dev server we have a webhook that logs any crash reports (if the user opts in)
![image](https://github.com/Astrabit-ST/Luminol/assets/54482069/1e97b407-5c0e-42fb-804d-21ecf85f79f8)

I was intending to add this for panics a while ago?

**Comment by white-axe** [comment]
I'll try making a graphical panic reporter
