### ISSUE TITLE
Website freezes when after I select a folder

### ISSUE THREAD

**Issue by aFrogThatExists** [Astrabit-ST/Luminol#8]
Steps to reproduce:

- Press new project
- Select an empty folder
- Then it freezes

![image](https://user-images.githubusercontent.com/54812998/229345031-e6433879-a688-4375-b836-3ec8cb17b536.png)

I think there is a bug somewhere but it could also be me doing something wrong =D

**Comment by Speak2Erase** [comment]
Thanks for reporting the issue! This isn't on you, luminol's webassembly support is incomplete right now. I'll see what I can do to fix it, though!
